import sgMail from '@sendgrid/mail';
import fs from 'fs';
import path from 'path';

interface EmailOptions {
  to: string;
  subject: string;
  html: string;
  text?: string;
  templateData?: Record<string, any>;
}

interface EmailTemplate {
  subject: string;
  html: string;
  text: string;
}

class EmailService {
  private isConfigured: boolean = false;

  constructor() {
    this.initialize();
  }

  private initialize() {
    if (process.env.EMAIL_ENABLED === 'true' && process.env.SENDGRID_API_KEY) {
      try {
        sgMail.setApiKey(process.env.SENDGRID_API_KEY);
        this.isConfigured = true;
        console.log('📧 Email service configured with SendGrid');
      } catch (error) {
        console.error('📧 Failed to configure email service:', error);
        this.isConfigured = false;
      }
    } else {
      console.log('📧 Email service not configured - emails will be logged only');
      this.isConfigured = false;
    }
  }

  private replaceTemplateVariables(template: string, data: Record<string, any>): string {
    let result = template;
    for (const [key, value] of Object.entries(data)) {
      const placeholder = new RegExp(`{{${key}}}`, 'g');
      result = result.replace(placeholder, String(value));
    }
    return result;
  }

  private getEmailTemplate(templateName: string): EmailTemplate {
    const templates: Record<string, EmailTemplate> = {
      welcome: {
        subject: 'Welcome to SmartPromptIQ Pro! 🚀',
        html: `
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Welcome to SmartPromptIQ Pro</title>
            <style>
              body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; background-color: #f8fafc; margin: 0; padding: 0; }
              .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 10px 30px rgba(0,0,0,0.1); }
              .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 40px 30px; text-align: center; }
              .header h1 { margin: 0; font-size: 28px; font-weight: bold; }
              .content { padding: 40px 30px; }
              .feature { display: flex; align-items: center; margin: 20px 0; padding: 15px; background-color: #f8fafc; border-radius: 8px; }
              .feature-icon { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; width: 40px; height: 40px; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin-right: 15px; font-weight: bold; }
              .cta-button { display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 15px 30px; text-decoration: none; border-radius: 8px; font-weight: bold; margin: 20px 0; }
              .footer { background-color: #f8fafc; padding: 20px 30px; text-align: center; color: #666; font-size: 14px; }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="header">
                <h1>🚀 Welcome to SmartPromptIQ Pro!</h1>
                <p>Your AI-powered prompt generation platform is ready!</p>
              </div>
              <div class="content">
                <h2>Hi {{name}},</h2>
                <p>Welcome to SmartPromptIQ Pro! We're excited to have you on board. Your account has been successfully created and you're ready to start generating amazing AI prompts.</p>

                <div class="feature">
                  <div class="feature-icon">✨</div>
                  <div>
                    <strong>Premium Templates</strong><br>
                    Access our library of professional templates designed by experts
                  </div>
                </div>

                <div class="feature">
                  <div class="feature-icon">🎯</div>
                  <div>
                    <strong>Smart Questionnaires</strong><br>
                    Answer targeted questions to get personalized prompt recommendations
                  </div>
                </div>

                <div class="feature">
                  <div class="feature-icon">🚀</div>
                  <div>
                    <strong>AI Generation</strong><br>
                    Get comprehensive, actionable strategies generated by advanced AI
                  </div>
                </div>

                <div class="feature">
                  <div class="feature-icon">🔧</div>
                  <div>
                    <strong>Refinement Tools</strong><br>
                    Fine-tune your prompts with our advanced refinement system
                  </div>
                </div>

                <p style="text-align: center;">
                  <a href="{{dashboardUrl}}" class="cta-button">Start Creating Prompts</a>
                </p>

                <p>If you have any questions, our support team is here to help. Just reply to this email!</p>

                <p>Best regards,<br>The SmartPromptIQ Pro Team</p>
              </div>
              <div class="footer">
                <p>© 2024 SmartPromptIQ Pro. All rights reserved.</p>
                <p>This email was sent to {{email}}. If you didn't sign up for this account, please ignore this email.</p>
              </div>
            </div>
          </body>
          </html>
        `,
        text: `Welcome to SmartPromptIQ Pro!

Hi {{name}},

Welcome to SmartPromptIQ Pro! We're excited to have you on board. Your account has been successfully created and you're ready to start generating amazing AI prompts.

What you can do now:
✨ Access Premium Templates - Professional templates designed by experts
🎯 Use Smart Questionnaires - Get personalized prompt recommendations
🚀 AI Generation - Comprehensive, actionable strategies from advanced AI
🔧 Refinement Tools - Fine-tune your prompts with advanced tools

Get started: {{dashboardUrl}}

If you have any questions, our support team is here to help. Just reply to this email!

Best regards,
The SmartPromptIQ Pro Team

© 2024 SmartPromptIQ Pro. All rights reserved.
This email was sent to {{email}}. If you didn't sign up for this account, please ignore this email.`
      },

      passwordReset: {
        subject: 'Reset Your SmartPromptIQ Pro Password 🔐',
        html: `
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Reset Your Password</title>
            <style>
              body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; background-color: #f8fafc; margin: 0; padding: 0; }
              .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 10px 30px rgba(0,0,0,0.1); }
              .header { background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); color: white; padding: 40px 30px; text-align: center; }
              .content { padding: 40px 30px; }
              .reset-button { display: inline-block; background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); color: white; padding: 15px 30px; text-decoration: none; border-radius: 8px; font-weight: bold; margin: 20px 0; }
              .security-notice { background-color: #fff3cd; border: 1px solid #ffeaa7; padding: 15px; border-radius: 8px; margin: 20px 0; }
              .footer { background-color: #f8fafc; padding: 20px 30px; text-align: center; color: #666; font-size: 14px; }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="header">
                <h1>🔐 Password Reset Request</h1>
              </div>
              <div class="content">
                <h2>Hi {{name}},</h2>
                <p>We received a request to reset the password for your SmartPromptIQ Pro account ({{email}}).</p>

                <p style="text-align: center;">
                  <a href="{{resetUrl}}" class="reset-button">Reset Your Password</a>
                </p>

                <div class="security-notice">
                  <strong>⚠️ Security Notice:</strong><br>
                  This password reset link will expire in {{expiryTime}} for your security. If you didn't request this reset, please ignore this email - your account remains secure.
                </div>

                <p>If the button doesn't work, copy and paste this link into your browser:</p>
                <p style="word-break: break-all; color: #666;">{{resetUrl}}</p>

                <p>If you didn't request this password reset, please ignore this email or contact our support team if you have concerns.</p>

                <p>Best regards,<br>The SmartPromptIQ Pro Team</p>
              </div>
              <div class="footer">
                <p>© 2024 SmartPromptIQ Pro. All rights reserved.</p>
                <p>For security reasons, this email was sent to {{email}}</p>
              </div>
            </div>
          </body>
          </html>
        `,
        text: `Password Reset Request - SmartPromptIQ Pro

Hi {{name}},

We received a request to reset the password for your SmartPromptIQ Pro account ({{email}}).

Reset your password here: {{resetUrl}}

⚠️ Security Notice:
This password reset link will expire in {{expiryTime}} for your security. If you didn't request this reset, please ignore this email - your account remains secure.

If you didn't request this password reset, please ignore this email or contact our support team if you have concerns.

Best regards,
The SmartPromptIQ Pro Team

© 2024 SmartPromptIQ Pro. All rights reserved.
For security reasons, this email was sent to {{email}}`
      },

      promptGenerated: {
        subject: '🎉 Your AI Prompt is Ready!',
        html: `
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Your AI Prompt is Ready</title>
            <style>
              body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; background-color: #f8fafc; margin: 0; padding: 0; }
              .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 10px 30px rgba(0,0,0,0.1); }
              .header { background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%); color: white; padding: 40px 30px; text-align: center; }
              .content { padding: 40px 30px; }
              .prompt-preview { background-color: #f8fafc; border-left: 4px solid #4facfe; padding: 20px; margin: 20px 0; border-radius: 0 8px 8px 0; }
              .view-button { display: inline-block; background: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%); color: white; padding: 15px 30px; text-decoration: none; border-radius: 8px; font-weight: bold; margin: 20px 0; }
              .stats { display: flex; justify-content: space-around; margin: 30px 0; }
              .stat { text-align: center; }
              .stat-number { font-size: 24px; font-weight: bold; color: #4facfe; }
              .footer { background-color: #f8fafc; padding: 20px 30px; text-align: center; color: #666; font-size: 14px; }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="header">
                <h1>🎉 Your AI Prompt is Ready!</h1>
                <p>{{category}} strategy generated successfully</p>
              </div>
              <div class="content">
                <h2>Hi {{name}},</h2>
                <p>Great news! Your personalized {{category}} prompt has been generated and is ready for you to use.</p>

                <div class="prompt-preview">
                  <h3>{{promptTitle}}</h3>
                  <p>{{promptPreview}}...</p>
                </div>

                <div class="stats">
                  <div class="stat">
                    <div class="stat-number">{{wordCount}}</div>
                    <div>Words</div>
                  </div>
                  <div class="stat">
                    <div class="stat-number">{{sections}}</div>
                    <div>Sections</div>
                  </div>
                  <div class="stat">
                    <div class="stat-number">{{readTime}}</div>
                    <div>Min Read</div>
                  </div>
                </div>

                <p style="text-align: center;">
                  <a href="{{promptUrl}}" class="view-button">View Full Prompt</a>
                </p>

                <p>Your prompt includes:</p>
                <ul>
                  <li>✅ Comprehensive strategy framework</li>
                  <li>✅ Actionable implementation steps</li>
                  <li>✅ Success metrics and KPIs</li>
                  <li>✅ Professional formatting</li>
                </ul>

                <p>You can continue to refine and customize your prompt in your dashboard.</p>

                <p>Happy prompting!<br>The SmartPromptIQ Pro Team</p>
              </div>
              <div class="footer">
                <p>© 2024 SmartPromptIQ Pro. All rights reserved.</p>
                <p>This prompt was generated for {{email}}</p>
              </div>
            </div>
          </body>
          </html>
        `,
        text: `Your AI Prompt is Ready! - SmartPromptIQ Pro

Hi {{name}},

Great news! Your personalized {{category}} prompt has been generated and is ready for you to use.

{{promptTitle}}
{{promptPreview}}...

Prompt Stats:
- {{wordCount}} words
- {{sections}} sections
- {{readTime}} minute read

View your full prompt: {{promptUrl}}

Your prompt includes:
✅ Comprehensive strategy framework
✅ Actionable implementation steps
✅ Success metrics and KPIs
✅ Professional formatting

You can continue to refine and customize your prompt in your dashboard.

Happy prompting!
The SmartPromptIQ Pro Team

© 2024 SmartPromptIQ Pro. All rights reserved.
This prompt was generated for {{email}}`
      },

      subscriptionUpgrade: {
        subject: '🚀 Welcome to {{planName}} - Your Upgrade is Active!',
        html: `
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Subscription Upgrade Confirmation</title>
            <style>
              body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; background-color: #f8fafc; margin: 0; padding: 0; }
              .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 10px 30px rgba(0,0,0,0.1); }
              .header { background: linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%); color: #333; padding: 40px 30px; text-align: center; }
              .content { padding: 40px 30px; }
              .feature-list { background-color: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0; }
              .feature-item { display: flex; align-items: center; margin: 10px 0; }
              .feature-icon { color: #10b981; margin-right: 10px; font-weight: bold; }
              .dashboard-button { display: inline-block; background: linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%); color: #333; padding: 15px 30px; text-decoration: none; border-radius: 8px; font-weight: bold; margin: 20px 0; }
              .footer { background-color: #f8fafc; padding: 20px 30px; text-align: center; color: #666; font-size: 14px; }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="header">
                <h1>🚀 Upgrade Successful!</h1>
                <p>Welcome to {{planName}}</p>
              </div>
              <div class="content">
                <h2>Hi {{name}},</h2>
                <p>Congratulations! Your account has been successfully upgraded to <strong>{{planName}}</strong>. You now have access to all the premium features.</p>

                <div class="feature-list">
                  <h3>Your New Features:</h3>
                  <div class="feature-item">
                    <span class="feature-icon">✓</span>
                    <span>{{generationsLimit}} prompt generations per month</span>
                  </div>
                  <div class="feature-item">
                    <span class="feature-icon">✓</span>
                    <span>Access to premium templates</span>
                  </div>
                  <div class="feature-item">
                    <span class="feature-icon">✓</span>
                    <span>Advanced AI refinement tools</span>
                  </div>
                  <div class="feature-item">
                    <span class="feature-icon">✓</span>
                    <span>Priority customer support</span>
                  </div>
                  <div class="feature-item">
                    <span class="feature-icon">✓</span>
                    <span>Export and save unlimited prompts</span>
                  </div>
                </div>

                <p style="text-align: center;">
                  <a href="{{dashboardUrl}}" class="cta-button">Get Started Now</a>
                </p>

                <p>We're excited to help you create amazing AI prompts with our platform!</p>

                <p>Best regards,<br>The SmartPromptIQ Pro Team</p>
              </div>
              <div class="footer">
                <p>© 2024 SmartPromptIQ Pro. All rights reserved.</p>
                <p>Manage your subscription: <a href="{{billingUrl}}">Billing Settings</a></p>
              </div>
            </div>
          </body>
          </html>
        `,
        text: `Upgrade Successful! - SmartPromptIQ Pro

Hi {{name}},

Congratulations! Your account has been successfully upgraded to {{planName}}. You now have access to all the premium features.

Your New Features:
✓ {{generationsLimit}} prompt generations per month
✓ Access to premium templates
✓ Advanced AI refinement tools
✓ Priority customer support
✓ Export and save unlimited prompts

Get started now: {{dashboardUrl}}

We're excited to help you create amazing AI prompts with our platform!

Best regards,
The SmartPromptIQ Pro Team

© 2024 SmartPromptIQ Pro. All rights reserved.
Manage your subscription: {{billingUrl}}`
      }
    };

    return templates[templateName] || templates.welcome;
  }

  async sendEmail(options: EmailOptions): Promise<boolean> {
    try {
      const fromEmail = process.env.SENDGRID_FROM_EMAIL || 'noreply@smartpromptiq.com';
      const fromName = process.env.SENDGRID_FROM_NAME || 'SmartPromptIQ Pro';

      const msg = {
        to: options.to,
        from: {
          email: fromEmail,
          name: fromName
        },
        subject: options.subject,
        text: options.text || options.html.replace(/<[^>]*>/g, ''),
        html: options.html
      };

      if (this.isConfigured) {
        await sgMail.send(msg);
        console.log(`📧 Email sent successfully to ${options.to}: ${options.subject}`);
        return true;
      } else {
        console.log(`📧 Email would be sent to ${options.to}: ${options.subject}`);
        console.log(`📧 Content preview: ${options.html.substring(0, 200)}...`);
        return true; // Return true for development purposes
      }
    } catch (error) {
      console.error('📧 Failed to send email:', error);
      return false;
    }
  }

  async sendTemplateEmail(
    to: string,
    templateName: string,
    templateData: Record<string, any>
  ): Promise<boolean> {
    try {
      const template = this.getEmailTemplate(templateName);

      const processedSubject = this.replaceTemplateVariables(template.subject, templateData);
      const processedHtml = this.replaceTemplateVariables(template.html, templateData);
      const processedText = this.replaceTemplateVariables(template.text, templateData);

      return await this.sendEmail({
        to,
        subject: processedSubject,
        html: processedHtml,
        text: processedText,
        templateData
      });
    } catch (error) {
      console.error(`📧 Failed to send template email (${templateName}):`, error);
      return false;
    }
  }

  // Convenience methods for common email types
  async sendWelcomeEmail(to: string, name: string): Promise<boolean> {
    const dashboardUrl = `${process.env.FRONTEND_URL}/dashboard`;
    return this.sendTemplateEmail(to, 'welcome', {
      name,
      email: to,
      dashboardUrl
    });
  }

  async sendPasswordResetEmail(to: string, name: string, resetToken: string): Promise<boolean> {
    const resetUrl = `${process.env.FRONTEND_URL}/reset-password?token=${resetToken}`;
    return this.sendTemplateEmail(to, 'passwordReset', {
      name,
      email: to,
      resetUrl,
      expiryTime: '24 hours'
    });
  }

  async sendPromptGeneratedEmail(
    to: string,
    name: string,
    promptData: {
      category: string;
      title: string;
      preview: string;
      wordCount: number;
      sections: number;
      readTime: number;
      promptId: string;
    }
  ): Promise<boolean> {
    const promptUrl = `${process.env.FRONTEND_URL}/dashboard?prompt=${promptData.promptId}`;
    return this.sendTemplateEmail(to, 'promptGenerated', {
      name,
      email: to,
      category: promptData.category,
      promptTitle: promptData.title,
      promptPreview: promptData.preview,
      wordCount: promptData.wordCount,
      sections: promptData.sections,
      readTime: promptData.readTime,
      promptUrl
    });
  }

  async sendSubscriptionUpgradeEmail(
    to: string,
    name: string,
    subscriptionData: {
      planName: string;
      generationsLimit: number;
      amount: string;
      billingCycle: string;
      nextBillingDate: string;
    }
  ): Promise<boolean> {
    const dashboardUrl = `${process.env.FRONTEND_URL}/dashboard`;
    const billingUrl = `${process.env.FRONTEND_URL}/billing`;

    return this.sendTemplateEmail(to, 'subscriptionUpgrade', {
      name,
      email: to,
      planName: subscriptionData.planName,
      generationsLimit: subscriptionData.generationsLimit,
      amount: subscriptionData.amount,
      billingCycle: subscriptionData.billingCycle,
      nextBillingDate: subscriptionData.nextBillingDate,
      dashboardUrl,
      billingUrl
    });
  }

  // Test email functionality
  async sendTestEmail(to: string): Promise<boolean> {
    return this.sendEmail({
      to,
      subject: '🧪 SmartPromptIQ Pro - Email Test',
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
          <h1 style="color: #4f46e5;">📧 Email Test Successful!</h1>
          <p>This is a test email from SmartPromptIQ Pro to verify that the email service is working correctly.</p>
          <p><strong>Timestamp:</strong> ${new Date().toISOString()}</p>
          <p><strong>Environment:</strong> ${process.env.NODE_ENV}</p>
          <p><strong>Service Status:</strong> ${this.isConfigured ? 'SendGrid Configured' : 'Mock Mode'}</p>
          <hr>
          <p style="color: #666; font-size: 14px;">© 2024 SmartPromptIQ Pro. All rights reserved.</p>
        </div>
      `
    });
  }

  getStatus(): { configured: boolean; provider: string } {
    return {
      configured: this.isConfigured,
      provider: this.isConfigured ? 'SendGrid' : 'Mock'
    };
  }
}

export default new EmailService();