/**
 * Centralized Voice Configuration
 * All ElevenLabs and OpenAI voice definitions in one place
 * NO REPETITION - Import this everywhere voices are needed
 */

// ElevenLabs Voice IDs (from ElevenLabs dashboard)
export const ELEVENLABS_VOICE_IDS = {
  // Female voices
  rachel: '21m00Tcm4TlvDq8ikWAM',
  domi: 'AZnzlk1XvdvUeBnXmlld',
  bella: 'EXAVITQu4vr4xnSDxMaL',
  elli: 'MF3mGyEYCl7XYWbV9V6O',
  charlotte: 'XB0fDUnXU5powFXDhCwa',
  matilda: 'XrExE9yKIg1WjnnlVkGX',
  emily: 'LcfcDJNUP1GQjkzn1xUU',
  jessie: 't0jbNlBVZ17f02VDIeMI',
  grace: 'oWAxZDx7w5VEj9dCyTzz',
  lily: 'pFZP5JQG7iQjIQuC4Bku',
  nicole: 'piTKgcLEGmPE4e6mEKli',
  sarah: 'EXAVITQu4vr4xnSDxMaL',
  // Male voices
  adam: 'pNInz6obpgDQGcFmaJgB',
  antoni: 'ErXwobaYiN019PkySvjV',
  josh: 'TxGEqnHWrfWFTfGW9XjX',
  arnold: 'VR6AewLTigWG4xSOukaG',
  sam: 'yoZ06aMxZJJ28mfd3POQ',
  callum: 'N2lVS1w4EtoT3dr4eOWO',
  clyde: '2EiwWnXFnvU5JabPnv8n',
  fin: 'D38z5RcWu1voky8WS1ja',
  brian: 'nPczCjzI2devNBz1zQrb',
  daniel: 'onwK4e9ZLuTAKqWW03F9',
  george: 'JBFqnCBsd6RMkjVDRZzb',
  liam: 'TX3LPaxmHKxFdv7VOQHJ',
  james: 'ZQe5CZNOzWyzPSCn5a3c',
  ethan: 'g5CIjZEefAph4nQFvHAz',
  harry: 'SOYHLrjzK2X1ezoPC6cr',
  michael: 'flq6f7yk4E4fJM5XTYuZ',
  thomas: 'GBv7mTt0atIp3Br8iCZE',
  patrick: 'ODq5zmih8GrVes37Dizd',
  charlie: 'IKne3meq5aSn9XLyUdCD',
} as const;

// Voice persona type
export interface VoicePersona {
  id: string;
  name: string;
  persona: string;
  tagline: string;
  description: string;
  vibe: string;
  gender: 'male' | 'female' | 'neutral';
  style: string;
  color: string;
  emoji: string;
  bestFor: string[];
  sampleLine: string;
  premium: boolean;
  category?: string;
}

// =============================================================
// ELEVENLABS PREMIUM VOICES - Ultra-realistic AI voices
// 25+ Professional voices for every use case!
// =============================================================
export const ELEVENLABS_VOICES: VoicePersona[] = [
  // ==================== FEMALE VOICES ====================
  {
    id: 'rachel',
    name: 'Rachel',
    persona: 'The Warm Teacher',
    tagline: 'Patient & nurturing guide',
    description: 'Ultra-realistic warm female voice - perfect for education and tutorials',
    vibe: 'Premium ElevenLabs quality',
    gender: 'female',
    style: 'teacher',
    color: 'from-teal-400 to-cyan-500',
    emoji: '👩‍🏫',
    bestFor: ['Education', 'Tutorials', 'Courses', 'Academy'],
    sampleLine: 'Let me walk you through this step by step...',
    premium: true,
    category: 'education',
  },
  {
    id: 'domi',
    name: 'Domi',
    persona: 'The Confident Pro',
    tagline: 'Strong & persuasive',
    description: 'Confident female voice - great for marketing and ads',
    vibe: 'Premium ElevenLabs quality',
    gender: 'female',
    style: 'marketing',
    color: 'from-blue-500 to-indigo-600',
    emoji: '💼',
    bestFor: ['Marketing', 'Ads', 'Sales', 'Pitches'],
    sampleLine: 'Transform your business starting today...',
    premium: true,
    category: 'marketing',
  },
  {
    id: 'bella',
    name: 'Bella',
    persona: 'The Wellness Guide',
    tagline: 'Soft & soothing',
    description: 'Calm expressive voice - perfect for meditation and wellness',
    vibe: 'Premium ElevenLabs quality',
    gender: 'female',
    style: 'calm',
    color: 'from-purple-400 to-pink-500',
    emoji: '🧘',
    bestFor: ['Meditation', 'Wellness', 'Relaxation', 'Sleep'],
    sampleLine: 'Take a deep breath and let go of tension...',
    premium: true,
    category: 'wellness',
  },
  {
    id: 'elli',
    name: 'Elli',
    persona: 'The Young Guide',
    tagline: 'Youthful & encouraging',
    description: 'Young playful female - perfect for education and tutorials',
    vibe: 'Premium ElevenLabs quality',
    gender: 'female',
    style: 'guide',
    color: 'from-pink-400 to-rose-500',
    emoji: '👧',
    bestFor: ['Education', 'Tutorials', 'Kids Content', 'Friendly'],
    sampleLine: 'This is going to be so much fun to learn!',
    premium: true,
    category: 'education',
  },
  {
    id: 'charlotte',
    name: 'Charlotte',
    persona: 'The British Scholar',
    tagline: 'Sophisticated elegance',
    description: 'British accent female - sophisticated and professional',
    vibe: 'Premium ElevenLabs quality',
    gender: 'female',
    style: 'scholarly',
    color: 'from-rose-400 to-red-500',
    emoji: '🇬🇧',
    bestFor: ['Professional', 'Academic', 'Luxury', 'Formal'],
    sampleLine: 'Allow me to elucidate the finer details...',
    premium: true,
    category: 'professional',
  },
  {
    id: 'matilda',
    name: 'Matilda',
    persona: 'The Warm Narrator',
    tagline: 'Friendly & inviting',
    description: 'Warm American female - perfect for friendly narration',
    vibe: 'Premium ElevenLabs quality',
    gender: 'female',
    style: 'narrator',
    color: 'from-orange-400 to-amber-500',
    emoji: '🌻',
    bestFor: ['Narration', 'Audiobooks', 'Friendly Content', 'Stories'],
    sampleLine: 'Welcome to our journey together...',
    premium: true,
    category: 'entertainment',
  },
  {
    id: 'emily',
    name: 'Emily',
    persona: 'The News Anchor',
    tagline: 'Clear & authoritative',
    description: 'Clear news anchor style - perfect for announcements',
    vibe: 'Premium ElevenLabs quality',
    gender: 'female',
    style: 'news',
    color: 'from-cyan-400 to-blue-500',
    emoji: '📺',
    bestFor: ['News', 'Announcements', 'Updates', 'Reports'],
    sampleLine: 'Breaking news: We have an exciting announcement...',
    premium: true,
    category: 'announcements',
  },
  {
    id: 'jessie',
    name: 'Jessie',
    persona: 'The Energetic Host',
    tagline: 'Upbeat & lively',
    description: 'High-energy female voice - great for exciting content',
    vibe: 'Premium ElevenLabs quality',
    gender: 'female',
    style: 'energetic',
    color: 'from-yellow-400 to-orange-500',
    emoji: '⚡',
    bestFor: ['Gaming', 'Sports', 'Entertainment', 'Promos'],
    sampleLine: "Get ready for something absolutely amazing!",
    premium: true,
    category: 'entertainment',
  },
  {
    id: 'grace',
    name: 'Grace',
    persona: 'The Elegant Presenter',
    tagline: 'Graceful & refined',
    description: 'Elegant sophisticated voice - ideal for luxury brands',
    vibe: 'Premium ElevenLabs quality',
    gender: 'female',
    style: 'elegant',
    color: 'from-violet-400 to-purple-600',
    emoji: '👑',
    bestFor: ['Luxury', 'Fashion', 'High-end', 'Sophisticated'],
    sampleLine: 'Experience the epitome of excellence...',
    premium: true,
    category: 'professional',
  },
  {
    id: 'lily',
    name: 'Lily',
    persona: 'The Sweet Companion',
    tagline: 'Gentle & caring',
    description: 'Sweet gentle voice - perfect for soft content',
    vibe: 'Premium ElevenLabs quality',
    gender: 'female',
    style: 'gentle',
    color: 'from-pink-300 to-rose-400',
    emoji: '🌸',
    bestFor: ['Wellness', 'ASMR', 'Gentle Content', 'Relaxation'],
    sampleLine: 'Close your eyes and relax...',
    premium: true,
    category: 'wellness',
  },
  {
    id: 'nicole',
    name: 'Nicole',
    persona: 'The Professional',
    tagline: 'Crisp & business-like',
    description: 'Professional business voice - ideal for corporate',
    vibe: 'Premium ElevenLabs quality',
    gender: 'female',
    style: 'business',
    color: 'from-slate-400 to-gray-600',
    emoji: '📊',
    bestFor: ['Corporate', 'Business', 'Presentations', 'Training'],
    sampleLine: "Let's review the key performance indicators...",
    premium: true,
    category: 'business',
  },
  // ==================== MALE VOICES ====================
  {
    id: 'adam',
    name: 'Adam',
    persona: 'The Authority',
    tagline: 'Deep & commanding',
    description: 'Deep authoritative male voice - ideal for corporate and documentary',
    vibe: 'Premium ElevenLabs quality',
    gender: 'male',
    style: 'professional',
    color: 'from-slate-600 to-gray-800',
    emoji: '🎙️',
    bestFor: ['Corporate', 'Documentary', 'Business', 'Leadership'],
    sampleLine: 'Welcome to a new era of innovation...',
    premium: true,
    category: 'business',
  },
  {
    id: 'sam',
    name: 'Sam',
    persona: 'The Storyteller',
    tagline: 'Warm & engaging',
    description: 'Warm engaging male voice - ideal for stories and podcasts',
    vibe: 'Premium ElevenLabs quality',
    gender: 'male',
    style: 'storytelling',
    color: 'from-amber-400 to-orange-500',
    emoji: '📖',
    bestFor: ['Audiobooks', 'Podcasts', 'Stories', 'Narratives'],
    sampleLine: 'Once upon a time, in a world not so different from ours...',
    premium: true,
    category: 'entertainment',
  },
  {
    id: 'josh',
    name: 'Josh',
    persona: 'The Young Pro',
    tagline: 'Fresh & dynamic',
    description: 'Young American male voice - great for tech and modern content',
    vibe: 'Premium ElevenLabs quality',
    gender: 'male',
    style: 'tech',
    color: 'from-green-400 to-emerald-500',
    emoji: '🚀',
    bestFor: ['Tech', 'Apps', 'Modern Content', 'Startups'],
    sampleLine: "Here's what makes this absolutely game-changing...",
    premium: true,
    category: 'tech',
  },
  {
    id: 'antoni',
    name: 'Antoni',
    persona: 'The Friendly Host',
    tagline: 'Natural & versatile',
    description: 'Friendly natural male - versatile for all content',
    vibe: 'Premium ElevenLabs quality',
    gender: 'male',
    style: 'friendly',
    color: 'from-indigo-400 to-purple-500',
    emoji: '😊',
    bestFor: ['General', 'Casual', 'Hosting', 'Conversations'],
    sampleLine: "Hey there! Let's dive into something exciting...",
    premium: true,
    category: 'general',
  },
  {
    id: 'arnold',
    name: 'Arnold',
    persona: 'The Action Hero',
    tagline: 'Bold & powerful',
    description: 'Strong powerful voice - perfect for action content',
    vibe: 'Premium ElevenLabs quality',
    gender: 'male',
    style: 'action',
    color: 'from-red-500 to-orange-600',
    emoji: '💪',
    bestFor: ['Action', 'Gaming', 'Trailers', 'Intense Content'],
    sampleLine: "It's time to take action and change the game!",
    premium: true,
    category: 'entertainment',
  },
  {
    id: 'callum',
    name: 'Callum',
    persona: 'The British Gentleman',
    tagline: 'Refined & distinguished',
    description: 'British male voice - sophisticated and polished',
    vibe: 'Premium ElevenLabs quality',
    gender: 'male',
    style: 'british',
    color: 'from-emerald-500 to-teal-600',
    emoji: '🎩',
    bestFor: ['Luxury', 'Documentary', 'British Content', 'Formal'],
    sampleLine: 'Good evening, and welcome to this extraordinary journey...',
    premium: true,
    category: 'professional',
  },
  {
    id: 'clyde',
    name: 'Clyde',
    persona: 'The Deep Voice',
    tagline: 'Rich & resonant',
    description: 'Deep resonant voice - great for dramatic narration',
    vibe: 'Premium ElevenLabs quality',
    gender: 'male',
    style: 'deep',
    color: 'from-purple-600 to-indigo-700',
    emoji: '🎭',
    bestFor: ['Drama', 'Trailers', 'Narration', 'Epic Content'],
    sampleLine: 'In the depths of the unknown, a story unfolds...',
    premium: true,
    category: 'entertainment',
  },
  {
    id: 'fin',
    name: 'Fin',
    persona: 'The Irish Charm',
    tagline: 'Warm & charismatic',
    description: 'Irish accent male - friendly and engaging',
    vibe: 'Premium ElevenLabs quality',
    gender: 'male',
    style: 'irish',
    color: 'from-green-500 to-emerald-600',
    emoji: '☘️',
    bestFor: ['Storytelling', 'Travel', 'Friendly Content', 'Casual'],
    sampleLine: "Well now, let me tell you something wonderful...",
    premium: true,
    category: 'entertainment',
  },
  {
    id: 'brian',
    name: 'Brian',
    persona: 'The Podcast Host',
    tagline: 'Conversational & smooth',
    description: 'Smooth conversational voice - perfect for podcasts',
    vibe: 'Premium ElevenLabs quality',
    gender: 'male',
    style: 'podcast',
    color: 'from-blue-400 to-cyan-500',
    emoji: '🎧',
    bestFor: ['Podcasts', 'Interviews', 'Conversations', 'Talk Shows'],
    sampleLine: "So here's the thing most people don't realize...",
    premium: true,
    category: 'entertainment',
  },
  {
    id: 'daniel',
    name: 'Daniel',
    persona: 'The News Reporter',
    tagline: 'Clear & professional',
    description: 'Professional reporter voice - clear and articulate',
    vibe: 'Premium ElevenLabs quality',
    gender: 'male',
    style: 'reporter',
    color: 'from-gray-500 to-slate-600',
    emoji: '📰',
    bestFor: ['News', 'Reports', 'Journalism', 'Announcements'],
    sampleLine: 'Reporting live with breaking developments...',
    premium: true,
    category: 'announcements',
  },
  {
    id: 'george',
    name: 'George',
    persona: 'The Wise Mentor',
    tagline: 'Thoughtful & wise',
    description: 'Mature wise voice - ideal for educational content',
    vibe: 'Premium ElevenLabs quality',
    gender: 'male',
    style: 'mentor',
    color: 'from-amber-500 to-yellow-600',
    emoji: '🎓',
    bestFor: ['Education', 'Wisdom', 'Philosophy', 'Mentoring'],
    sampleLine: 'The key insight here is something profound...',
    premium: true,
    category: 'education',
  },
  {
    id: 'liam',
    name: 'Liam',
    persona: 'The Young Entrepreneur',
    tagline: 'Ambitious & driven',
    description: 'Young ambitious voice - great for startup content',
    vibe: 'Premium ElevenLabs quality',
    gender: 'male',
    style: 'entrepreneur',
    color: 'from-teal-400 to-green-500',
    emoji: '💡',
    bestFor: ['Startups', 'Innovation', 'Tech', 'Business'],
    sampleLine: "This is how we're disrupting the entire industry...",
    premium: true,
    category: 'tech',
  },
  {
    id: 'james',
    name: 'James',
    persona: 'The Executive',
    tagline: 'Polished & executive',
    description: 'Executive-level voice - perfect for leadership content',
    vibe: 'Premium ElevenLabs quality',
    gender: 'male',
    style: 'executive',
    color: 'from-slate-500 to-gray-700',
    emoji: '🏢',
    bestFor: ['Corporate', 'Leadership', 'Executive', 'Board'],
    sampleLine: 'Our strategic vision for the future is clear...',
    premium: true,
    category: 'business',
  },
  {
    id: 'ethan',
    name: 'Ethan',
    persona: 'The Gamer',
    tagline: 'Energetic & fun',
    description: 'High-energy gaming voice - perfect for entertainment',
    vibe: 'Premium ElevenLabs quality',
    gender: 'male',
    style: 'gamer',
    color: 'from-purple-500 to-pink-500',
    emoji: '🎮',
    bestFor: ['Gaming', 'Entertainment', 'Youth Content', 'Fun'],
    sampleLine: "Let's gooo! This is about to be epic!",
    premium: true,
    category: 'entertainment',
  },
  {
    id: 'harry',
    name: 'Harry',
    persona: 'The Charmer',
    tagline: 'Smooth & charismatic',
    description: 'Charismatic smooth voice - great for persuasive content',
    vibe: 'Premium ElevenLabs quality',
    gender: 'male',
    style: 'charming',
    color: 'from-rose-400 to-pink-500',
    emoji: '✨',
    bestFor: ['Marketing', 'Persuasion', 'Romance', 'Charm'],
    sampleLine: "You're going to absolutely love what I'm about to show you...",
    premium: true,
    category: 'marketing',
  },
];

// =============================================================
// OPENAI STANDARD VOICES - Good quality fallback
// =============================================================
export const OPENAI_VOICES: VoicePersona[] = [
  {
    id: 'nova',
    name: 'Victoria Sterling',
    persona: 'The CEO',
    tagline: 'Commanding boardroom presence',
    description: 'Sounds like a Fortune 500 executive - confident, polished, and persuasive',
    vibe: 'Think: Oprah meets TED Talk presenter',
    gender: 'female',
    style: 'professional',
    color: 'from-purple-500 to-indigo-500',
    emoji: '👩‍💼',
    bestFor: ['Pitches', 'Corporate', 'Leadership'],
    sampleLine: 'Let me tell you why this changes everything...',
    premium: false,
  },
  {
    id: 'onyx',
    name: 'Marcus Vox',
    persona: 'The Movie Trailer Guy',
    tagline: 'Epic cinematic narrator',
    description: 'Deep, dramatic voice that makes everything sound like a blockbuster',
    vibe: 'Think: Movie trailer legend Don LaFontaine',
    gender: 'male',
    style: 'dramatic',
    color: 'from-slate-600 to-gray-800',
    emoji: '🎬',
    bestFor: ['Trailers', 'Gaming', 'Dramatic Content'],
    sampleLine: 'In a world where innovation meets destiny...',
    premium: false,
  },
  {
    id: 'echo',
    name: 'Jake Summers',
    persona: 'The Best Friend',
    tagline: 'Warm, relatable, trustworthy',
    description: 'Like your supportive best friend explaining things over coffee',
    vibe: 'Think: Ryan Reynolds casual charm',
    gender: 'male',
    style: 'friendly',
    color: 'from-amber-500 to-orange-500',
    emoji: '☕',
    bestFor: ['Tutorials', 'Podcasts', 'Casual Content'],
    sampleLine: "Okay, here's the thing you need to know...",
    premium: false,
  },
  {
    id: 'shimmer',
    name: 'Luna Serene',
    persona: 'The Wellness Guide',
    tagline: 'Calm, soothing, peaceful',
    description: 'Gentle voice perfect for meditation, wellness, and ASMR content',
    vibe: 'Think: Calm app narrator meets spa atmosphere',
    gender: 'female',
    style: 'calm',
    color: 'from-teal-400 to-cyan-500',
    emoji: '🧘',
    bestFor: ['Meditation', 'Wellness', 'Sleep Content'],
    sampleLine: "Take a deep breath. You're exactly where you need to be...",
    premium: false,
  },
  {
    id: 'alloy',
    name: 'Alex Dynamo',
    persona: 'The Hype Machine',
    tagline: 'High-energy excitement',
    description: 'Pumped up, enthusiastic voice that gets people excited',
    vibe: 'Think: Sports announcer meets Gary Vaynerchuk',
    gender: 'neutral',
    style: 'energetic',
    color: 'from-red-500 to-pink-500',
    emoji: '🔥',
    bestFor: ['Ads', 'Promos', 'Sports', 'Gaming'],
    sampleLine: "THIS is the moment you've been waiting for!",
    premium: false,
  },
  {
    id: 'fable',
    name: 'Sage Storyteller',
    persona: 'The Narrator',
    tagline: 'Master storyteller',
    description: 'Rich, expressive voice perfect for audiobooks and documentaries',
    vibe: 'Think: Morgan Freeman meets David Attenborough',
    gender: 'neutral',
    style: 'storytelling',
    color: 'from-emerald-500 to-green-600',
    emoji: '📖',
    bestFor: ['Audiobooks', 'Documentaries', 'Stories'],
    sampleLine: 'And so our journey begins, in a place not so different from here...',
    premium: false,
  },
];

// =============================================================
// VOICE PRESETS - Optimized settings for different use cases
// =============================================================
export const VOICE_PRESETS = {
  natural: {
    name: 'Natural',
    description: 'Balanced & versatile - great for most content',
    stability: 0.5,
    similarity_boost: 0.75,
    style: 0.0,
    use_speaker_boost: true,
  },
  clear: {
    name: 'Clear',
    description: 'High clarity - ideal for educational content',
    stability: 0.7,
    similarity_boost: 0.8,
    style: 0.0,
    use_speaker_boost: true,
  },
  expressive: {
    name: 'Expressive',
    description: 'More emotion & variation - great for storytelling',
    stability: 0.3,
    similarity_boost: 0.85,
    style: 0.5,
    use_speaker_boost: true,
  },
  dramatic: {
    name: 'Dramatic',
    description: 'Maximum expression - perfect for dramatic narration',
    stability: 0.4,
    similarity_boost: 0.9,
    style: 0.8,
    use_speaker_boost: true,
  },
  calm: {
    name: 'Calm',
    description: 'Stable & soothing - ideal for meditation & relaxation',
    stability: 0.8,
    similarity_boost: 0.7,
    style: 0.0,
    use_speaker_boost: false,
  },
} as const;

// =============================================================
// VOICE CATEGORIES - Organized by use case (25+ voices!)
// =============================================================
export const VOICE_CATEGORIES = {
  academy: ['rachel', 'elli', 'george', 'sam', 'matilda'],
  education: ['rachel', 'elli', 'charlotte', 'george', 'adam'],
  marketing: ['domi', 'harry', 'emily', 'josh', 'liam'],
  meditation: ['bella', 'lily', 'rachel', 'sam'],
  storytelling: ['sam', 'fin', 'clyde', 'matilda', 'charlotte'],
  business: ['adam', 'james', 'nicole', 'charlotte', 'daniel'],
  entertainment: ['ethan', 'jessie', 'arnold', 'brian', 'sam'],
  tech: ['josh', 'liam', 'adam', 'antoni', 'daniel'],
  wellness: ['bella', 'lily', 'rachel', 'grace'],
  general: ['antoni', 'rachel', 'adam', 'sam', 'emily'],
  gaming: ['ethan', 'arnold', 'jessie', 'josh'],
  podcast: ['brian', 'sam', 'antoni', 'rachel', 'fin'],
  luxury: ['grace', 'callum', 'charlotte', 'james'],
  news: ['emily', 'daniel', 'adam', 'nicole'],
  action: ['arnold', 'clyde', 'ethan', 'josh'],
  kids: ['elli', 'lily', 'matilda', 'jessie'],
  corporate: ['adam', 'james', 'nicole', 'charlotte', 'daniel'],
  documentary: ['adam', 'clyde', 'callum', 'sam', 'george'],
} as const;

// =============================================================
// HELPER FUNCTIONS
// =============================================================

/**
 * Get voice by ID from either ElevenLabs or OpenAI
 */
export function getVoiceById(id: string): VoicePersona | undefined {
  return ELEVENLABS_VOICES.find(v => v.id === id) || OPENAI_VOICES.find(v => v.id === id);
}

/**
 * Get voices for a specific category
 */
export function getVoicesForCategory(category: keyof typeof VOICE_CATEGORIES): VoicePersona[] {
  const voiceIds = VOICE_CATEGORIES[category] || VOICE_CATEGORIES.general;
  return voiceIds.map(id => getVoiceById(id)).filter(Boolean) as VoicePersona[];
}

/**
 * Get the best voice for a content type
 */
export function getBestVoiceForContent(contentType: string): VoicePersona {
  const categoryMap: Record<string, keyof typeof VOICE_CATEGORIES> = {
    lesson: 'academy',
    course: 'academy',
    tutorial: 'education',
    meditation: 'meditation',
    story: 'storytelling',
    podcast: 'storytelling',
    pitch: 'marketing',
    ad: 'marketing',
    corporate: 'business',
    announcement: 'business',
    app: 'tech',
    tech: 'tech',
    wellness: 'wellness',
  };

  const category = categoryMap[contentType.toLowerCase()] || 'general';
  const voices = getVoicesForCategory(category);
  return voices[0] || ELEVENLABS_VOICES[0];
}

/**
 * Get all voices (ElevenLabs first, then OpenAI)
 */
export function getAllVoices(): VoicePersona[] {
  return [...ELEVENLABS_VOICES, ...OPENAI_VOICES];
}

/**
 * Get ElevenLabs voice ID for API calls
 */
export function getElevenLabsVoiceId(voiceKey: string): string {
  return ELEVENLABS_VOICE_IDS[voiceKey as keyof typeof ELEVENLABS_VOICE_IDS] || ELEVENLABS_VOICE_IDS.rachel;
}

// Default export for convenience
export default {
  ELEVENLABS_VOICES,
  OPENAI_VOICES,
  VOICE_PRESETS,
  VOICE_CATEGORIES,
  ELEVENLABS_VOICE_IDS,
  getVoiceById,
  getVoicesForCategory,
  getBestVoiceForContent,
  getAllVoices,
  getElevenLabsVoiceId,
};
