import express from 'express';
import cors from 'cors';

const app = express();
const PORT = 3001;

// Basic middleware
app.use(cors({
  origin: 'http://localhost:5173',
  credentials: true
}));

app.use(express.json());

// Health check
app.get('/health', (req, res) => {
  res.json({
    status: 'healthy',
    timestamp: new Date().toISOString(),
    message: 'SmartPromptIQ Server is running!'
  });
});

// Mock auth endpoints
app.post('/api/auth/register', (req, res) => {
  res.json({
    message: 'Registration successful (demo mode)',
    user: { id: '1', name: req.body.name, email: req.body.email },
    token: 'demo-jwt-token'
  });
});

app.post('/api/auth/login', (req, res) => {
  res.json({
    message: 'Login successful (demo mode)',
    user: { id: '1', name: 'Demo User', email: req.body.email },
    token: 'demo-jwt-token'
  });
});

app.get('/api/auth/me', (req, res) => {
  res.json({
    user: { id: '1', name: 'Demo User', email: 'demo@smartpromptiq.com' }
  });
});

// Mock AI generation endpoint
app.post('/api/generate', (req, res) => {
  const { prompt } = req.body;
  res.json({
    message: 'Prompt generated successfully (demo mode)',
    generatedOutput: \This is a demo response to: \"\\". In production, this would be generated by AI.\,
    metadata: { tokensUsed: 100, cost: 0.002 }
  });
});

// Start server
app.listen(PORT, () => {
  console.log(\🚀 SmartPromptIQ Server running on http://localhost:\\);
  console.log(\✅ Health check: http://localhost:\/health\);
  console.log(\🌐 Frontend: http://localhost:5173\);
});
