import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  X,
  Copy,
  Check,
  ExternalLink,
  Rocket,
  ChevronRight,
  Sparkles,
  Code2,
  Play,
  ArrowRight,
  CheckCircle2,
  Clipboard,
  Globe,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';

interface Platform {
  id: string;
  name: string;
  logo: string;
  color: string;
  affiliateUrl: string;
  techStack: string[];
  deployTime: string;
}

interface DeploymentModalProps {
  isOpen: boolean;
  onClose: () => void;
  platform: Platform | null;
  blueprintPrompt?: string;
  appName?: string;
}

export const DeploymentModal: React.FC<DeploymentModalProps> = ({
  isOpen,
  onClose,
  platform,
  blueprintPrompt,
  appName = 'My App',
}) => {
  const { toast } = useToast();
  const [currentStep, setCurrentStep] = useState(1);
  const [copied, setCopied] = useState(false);
  const [platformOpened, setPlatformOpened] = useState(false);

  // Reset state when modal opens
  useEffect(() => {
    if (isOpen) {
      setCurrentStep(1);
      setCopied(false);
      setPlatformOpened(false);
    }
  }, [isOpen]);

  if (!isOpen || !platform) return null;

  // Generate the deployment prompt based on platform
  const generateDeploymentPrompt = () => {
    const basePrompt = blueprintPrompt || `Build me a modern web application called "${appName}".`;

    const platformSpecificInstructions: Record<string, string> = {
      replit: `
# SmartPromptIQ App Blueprint
# Deploy to Replit

${basePrompt}

## Technical Requirements:
- Use ${(platform.techStack || []).slice(0, 3).join(', ') || 'modern technologies'} for the tech stack
- Create a responsive, mobile-first design
- Include proper error handling
- Add loading states for async operations
- Structure code in a clean, maintainable way

## Project Structure:
- /src - Main source code
- /public - Static assets
- /components - Reusable UI components
- /pages or /routes - Application pages

## Getting Started:
1. This prompt was generated by SmartPromptIQ
2. Use Replit's AI (Ghostwriter) to help implement features
3. Click "Run" to see your app in action
4. Deploy when ready using Replit Deployments

Let's build something amazing!
`,
      bolt: `
# SmartPromptIQ App Blueprint
# Deploy to Bolt.new

${basePrompt}

## Requirements:
- Full-stack application with React frontend
- Node.js/Express backend if needed
- PostgreSQL database for data persistence
- Tailwind CSS for styling
- Modern, responsive UI

## Key Features to Implement:
- User authentication (if applicable)
- CRUD operations
- Real-time updates where needed
- Mobile-responsive design

Generated by SmartPromptIQ - Your AI Prompt Engineering Partner
`,
      lovable: `
# SmartPromptIQ App Blueprint
# Deploy to Lovable.dev

${basePrompt}

## Design Requirements:
- Beautiful, modern UI with smooth animations
- Consistent color scheme and typography
- Intuitive user experience
- Responsive across all devices

## Technical Stack:
- React with TypeScript
- Tailwind CSS for styling
- Supabase for backend (if needed)
- Framer Motion for animations

Created with SmartPromptIQ
`,
      v0: `
# SmartPromptIQ UI Blueprint
# Generate with v0.dev

${basePrompt}

## UI Requirements:
- Use shadcn/ui components
- Clean, minimalist design
- Dark mode support
- Responsive layout
- Accessible components

## Component Guidelines:
- Follow React best practices
- Use TypeScript for type safety
- Implement proper ARIA labels
- Add hover and focus states

Powered by SmartPromptIQ
`,
      shopify: `
# SmartPromptIQ E-Commerce Blueprint
# Build with Shopify

${basePrompt}

## Store Requirements:
- Professional e-commerce design
- Product catalog with categories
- Shopping cart & checkout flow
- Payment processing (Stripe/PayPal)
- Order management system

## Key Features:
- Product search & filtering
- Customer accounts
- Inventory tracking
- Email notifications
- Mobile-responsive storefront

## Shopify Apps to Consider:
- Reviews & ratings
- Email marketing
- SEO optimization
- Analytics & reporting

Created with SmartPromptIQ - Your E-Commerce Partner
`,
      webflow: `
# SmartPromptIQ Design Blueprint
# Build with Webflow

${basePrompt}

## Design Requirements:
- Clean, modern visual design
- Smooth scroll animations
- Interactive hover effects
- Responsive breakpoints (Desktop, Tablet, Mobile)

## CMS Structure:
- Dynamic content collections
- Filterable blog/portfolio
- Team members section
- Testimonials carousel

## Best Practices:
- Use Webflow's built-in animations
- Implement proper SEO settings
- Add form integrations
- Connect to analytics

Designed with SmartPromptIQ
`,
      vercel: `
# SmartPromptIQ Deployment Blueprint
# Deploy to Vercel

${basePrompt}

## Technical Stack:
- Next.js 14 with App Router
- TypeScript for type safety
- Tailwind CSS for styling
- Vercel Postgres or Supabase for database

## Vercel Features to Use:
- Edge Functions for APIs
- Image Optimization
- Analytics & Web Vitals
- Preview Deployments

## Environment Setup:
- Configure environment variables
- Set up database connection
- Add API routes
- Enable ISR/SSG where appropriate

Deployed with SmartPromptIQ + Vercel
`,
      supabase: `
# SmartPromptIQ Backend Blueprint
# Build with Supabase

${basePrompt}

## Database Schema:
- Users table with auth integration
- Main data tables with RLS policies
- Foreign key relationships
- Indexes for performance

## Supabase Features:
- Row Level Security (RLS)
- Real-time subscriptions
- Storage for file uploads
- Edge Functions for serverless

## Authentication:
- Email/password login
- OAuth providers (Google, GitHub)
- Magic link login
- Session management

Powered by SmartPromptIQ + Supabase
`,
      railway: `
# SmartPromptIQ Deployment Blueprint
# Deploy to Railway

${basePrompt}

## Infrastructure:
- Web service for the application
- PostgreSQL database
- Redis for caching (optional)
- Environment variables

## Railway Features:
- Auto-scaling
- Health checks
- Cron jobs
- Team collaboration

## Deployment Setup:
- Configure nixpacks or Dockerfile
- Set up database migrations
- Add monitoring
- Enable auto-deploy from GitHub

Built with SmartPromptIQ - Deployed on Railway
`,
      digitalocean: `
# SmartPromptIQ Cloud Blueprint
# Deploy to DigitalOcean

${basePrompt}

## Infrastructure Options:
- App Platform for easy deployment
- Droplets for full control
- Managed Kubernetes for scale
- Spaces for object storage

## Recommended Setup:
- Load balancer for traffic
- Managed database (PostgreSQL)
- CDN for static assets
- Monitoring & alerts

## Security:
- Firewall rules
- SSL certificates
- VPC networking
- Backup policies

Deployed with SmartPromptIQ on DigitalOcean
`,
      cursor: `
# SmartPromptIQ Development Blueprint
# Build with Cursor AI

${basePrompt}

## Development Workflow:
1. Open this prompt in Cursor
2. Use Cmd+K for inline AI edits
3. Use Cmd+L for chat about code
4. Let AI help with refactoring

## Code Structure:
- Modern TypeScript
- Clean architecture
- Well-documented functions
- Comprehensive tests

## Best Practices:
- Use AI for code review
- Generate tests with AI
- Refactor with confidence
- Debug faster with AI

Built with SmartPromptIQ + Cursor AI
`,
      flutterflow: `
# SmartPromptIQ Mobile Blueprint
# Build with FlutterFlow

${basePrompt}

## App Structure:
- Beautiful native UI
- Responsive layouts
- Custom animations
- Navigation flows

## Backend Integration:
- Firebase Authentication
- Firestore Database
- Cloud Functions
- Push Notifications

## Features to Build:
- User onboarding flow
- Dashboard screens
- Settings & profile
- Data visualization

Created with SmartPromptIQ - Built on FlutterFlow
`,
      zapier: `
# SmartPromptIQ Automation Blueprint
# Automate with Zapier

${basePrompt}

## Automation Workflows:
- New user onboarding emails
- CRM integration
- Slack notifications
- Google Sheets logging

## Recommended Zaps:
- Form submission → Database
- New order → Notification
- Weekly reports → Email
- Social posts → Schedule

## Integration Ideas:
- Connect to 5000+ apps
- Multi-step workflows
- Conditional logic
- Webhooks for custom apps

Automated with SmartPromptIQ + Zapier
`,
      cloudflare: `
# SmartPromptIQ Performance Blueprint
# Deploy with Cloudflare

${basePrompt}

## Cloudflare Services:
- Pages for static hosting
- Workers for serverless
- R2 for object storage
- D1 for edge database

## Performance Features:
- Global CDN
- Edge caching
- Image optimization
- Argo for faster routing

## Security:
- DDoS protection
- WAF rules
- Bot management
- SSL/TLS encryption

Secured with SmartPromptIQ + Cloudflare
`,
      planetscale: `
# SmartPromptIQ Database Blueprint
# Build with PlanetScale

${basePrompt}

## Database Design:
- Normalized schema
- Proper indexes
- Foreign key patterns
- Efficient queries

## PlanetScale Features:
- Database branching
- Non-blocking schema changes
- Automatic backups
- Query insights

## Integration:
- Prisma ORM setup
- Connection pooling
- Read replicas
- Deploy requests workflow

Data powered by SmartPromptIQ + PlanetScale
`,
      neon: `
# SmartPromptIQ Database Blueprint
# Build with Neon Postgres

${basePrompt}

## Database Setup:
- Serverless PostgreSQL
- Branching for development
- Auto-suspend for cost savings
- Point-in-time recovery

## Schema Design:
- Proper data types
- Constraints & validation
- Indexes for performance
- RLS policies

## Integration:
- Prisma/Drizzle ORM
- Connection string setup
- Pooler for serverless
- Migrations workflow

Powered by SmartPromptIQ + Neon
`,
      default: `
# SmartPromptIQ App Blueprint

${basePrompt}

## Technical Requirements:
- Modern tech stack: ${platform.techStack.join(', ')}
- Responsive design
- Clean code architecture
- Production-ready quality

## Features:
- User-friendly interface
- Proper error handling
- Loading states
- Optimized performance

Generated by SmartPromptIQ - Transform your ideas into apps!
`,
    };

    return platformSpecificInstructions[platform.id] || platformSpecificInstructions.default;
  };

  const deploymentPrompt = generateDeploymentPrompt();

  const handleCopyPrompt = async () => {
    try {
      await navigator.clipboard.writeText(deploymentPrompt);
      setCopied(true);
      setCurrentStep(2);
      toast({
        title: 'Prompt Copied!',
        description: 'Your app blueprint is ready to paste',
      });
      setTimeout(() => setCopied(false), 3000);
    } catch (err) {
      toast({
        title: 'Copy Failed',
        description: 'Please try again or manually select the text',
        variant: 'destructive',
      });
    }
  };

  const handleOpenPlatform = () => {
    window.open(platform.affiliateUrl, '_blank');
    setPlatformOpened(true);
    setCurrentStep(3);
    toast({
      title: `${platform.name} Opening`,
      description: 'Paste your prompt to start building!',
    });
  };

  const steps = [
    {
      number: 1,
      title: 'Copy Your Blueprint',
      description: 'Copy the AI-optimized prompt for your app',
      icon: Clipboard,
      action: handleCopyPrompt,
      actionLabel: copied ? 'Copied!' : 'Copy Prompt',
      isComplete: copied || currentStep > 1,
    },
    {
      number: 2,
      title: `Open ${platform.name}`,
      description: `Launch ${platform.name} to start building`,
      icon: ExternalLink,
      action: handleOpenPlatform,
      actionLabel: `Open ${platform.name}`,
      isComplete: platformOpened || currentStep > 2,
    },
    {
      number: 3,
      title: 'Paste & Build',
      description: 'Paste the prompt and watch your app come to life',
      icon: Play,
      action: onClose,
      actionLabel: 'Done',
      isComplete: false,
    },
  ];

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm"
        onClick={onClose}
      >
        <motion.div
          initial={{ scale: 0.9, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          exit={{ scale: 0.9, opacity: 0 }}
          className="relative w-full max-w-2xl bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl border border-slate-700 shadow-2xl overflow-hidden"
          onClick={(e) => e.stopPropagation()}
        >
          {/* Header */}
          <div className={`p-6 bg-gradient-to-r ${platform.color}`}>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <div className="w-14 h-14 rounded-xl bg-white/20 flex items-center justify-center text-3xl">
                  {platform.logo}
                </div>
                <div>
                  <h2 className="text-2xl font-bold text-white">Deploy to {platform.name}</h2>
                  <p className="text-white/80">Estimated time: {platform.deployTime}</p>
                </div>
              </div>
              <button
                onClick={onClose}
                className="p-2 rounded-lg bg-white/10 hover:bg-white/20 transition-colors"
              >
                <X className="w-5 h-5 text-white" />
              </button>
            </div>
          </div>

          {/* Steps */}
          <div className="p-6 space-y-4">
            {steps.map((step, index) => {
              const Icon = step.icon;
              const isActive = currentStep === step.number;
              const isComplete = step.isComplete;

              return (
                <motion.div
                  key={step.number}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: index * 0.1 }}
                  className={`p-4 rounded-xl border transition-all ${
                    isActive
                      ? 'bg-purple-500/10 border-purple-500/50'
                      : isComplete
                      ? 'bg-green-500/10 border-green-500/30'
                      : 'bg-slate-800/50 border-slate-700'
                  }`}
                >
                  <div className="flex items-center gap-4">
                    <div
                      className={`w-10 h-10 rounded-full flex items-center justify-center ${
                        isComplete
                          ? 'bg-green-500'
                          : isActive
                          ? 'bg-purple-500'
                          : 'bg-slate-700'
                      }`}
                    >
                      {isComplete ? (
                        <CheckCircle2 className="w-5 h-5 text-white" />
                      ) : (
                        <span className="text-white font-bold">{step.number}</span>
                      )}
                    </div>

                    <div className="flex-1">
                      <h3 className={`font-semibold ${isComplete ? 'text-green-400' : 'text-white'}`}>
                        {step.title}
                      </h3>
                      <p className="text-sm text-gray-400">{step.description}</p>
                    </div>

                    {isActive && (
                      <Button
                        onClick={step.action}
                        className={`${
                          step.number === 1 && copied
                            ? 'bg-green-500 hover:bg-green-600'
                            : 'bg-purple-500 hover:bg-purple-600'
                        }`}
                      >
                        {step.number === 1 && copied ? (
                          <Check className="w-4 h-4 mr-2" />
                        ) : (
                          <Icon className="w-4 h-4 mr-2" />
                        )}
                        {step.actionLabel}
                      </Button>
                    )}
                  </div>
                </motion.div>
              );
            })}
          </div>

          {/* Prompt Preview */}
          <div className="px-6 pb-6">
            <div className="p-4 bg-slate-900/80 rounded-xl border border-slate-700">
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2">
                  <Code2 className="w-4 h-4 text-purple-400" />
                  <span className="text-sm font-medium text-gray-300">Your App Blueprint</span>
                </div>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleCopyPrompt}
                  className="text-gray-400 hover:text-white"
                >
                  {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                </Button>
              </div>
              <div className="max-h-32 overflow-y-auto">
                <pre className="text-xs text-gray-400 whitespace-pre-wrap font-mono">
                  {(deploymentPrompt || '').slice(0, 500)}...
                </pre>
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="px-6 pb-6">
            <div className="flex items-center justify-between p-4 bg-gradient-to-r from-purple-500/10 to-pink-500/10 rounded-xl border border-purple-500/20">
              <div className="flex items-center gap-3">
                <Sparkles className="w-5 h-5 text-purple-400" />
                <div>
                  <p className="text-sm font-medium text-white">Pro Tip</p>
                  <p className="text-xs text-gray-400">
                    After pasting, ask the AI to add specific features or modify the design!
                  </p>
                </div>
              </div>
              {platformOpened && (
                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleOpenPlatform}
                  className="border-purple-500/30 text-purple-400"
                >
                  <Globe className="w-4 h-4 mr-2" />
                  Reopen
                </Button>
              )}
            </div>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
};

export default DeploymentModal;
